using System.Globalization;
using System.Text;
using Microsoft.EntityFrameworkCore;
using MyCup.Data;
using MyCup.DTOs.Championships;
using MyCup.DTOs.Common;
using MyCup.DTOs.Teams;
using MyCup.Errors;
using MyCup.Models;
using MyCup.Services.Authorization;
using MyCup.Services.Fixtures;

namespace MyCup.Services;

/// <summary>
/// Service responsible for championship business rules. The championship is an aggregate root that also
/// manages its team pool, rules, and player enrollments (PlayerChampionship). Phases/rounds/matches are
/// generated by the fixture engine (BE-008) and only read here for status/standings.
/// </summary>
public class ChampionshipsService
{
    private const int DefaultWinPoints = 3;
    private const int DefaultDrawPoints = 1;

    private readonly AppDbContext _context;
    private readonly UniverseAuthorizer _authorizer;

    public ChampionshipsService(AppDbContext context, UniverseAuthorizer authorizer)
    {
        _context = context;
        _authorizer = authorizer;
    }

    /// <summary>Requires the current user to be at least admin in the championship's universe.</summary>
    private async Task RequireChampionshipAdminAsync(int championshipId)
    {
        var universeId = await _context.Championships
            .Where(c => c.Id == championshipId)
            .Select(c => (int?)c.UniverseId)
            .FirstOrDefaultAsync();

        if (universeId is not int id)
            throw new NotFoundException("Campeonato não encontrado");

        await _authorizer.RequireRoleAsync(id, UniverseRole.Admin);
    }

    // ---------------------------------------------------------------------
    // Championship CRUD
    // ---------------------------------------------------------------------

    public async Task<int> CreateChampionshipAsync(CreateChampionshipDto dto)
    {
        var universeExists = await _context.Universes.AnyAsync(u => u.Id == dto.UniverseId);
        if (!universeExists)
            throw new NotFoundException("Universo não encontrado");

        var formatExists = await _context.Formats.AnyAsync(f => f.Id == dto.FormatId);
        if (!formatExists)
            throw new NotFoundException("Formato não encontrado");

        await _authorizer.RequireRoleAsync(dto.UniverseId, UniverseRole.Admin);

        Championship championship = new()
        {
            Name = dto.Name,
            UniverseId = dto.UniverseId,
            FormatId = dto.FormatId,
            Distribution = dto.Distribution,
            Slug = await GenerateUniqueSlugAsync(dto.Name, dto.UniverseId)
        };

        _context.Championships.Add(championship);
        await _context.SaveChangesAsync();

        return championship.Id;
    }

    public async Task<List<ChampionshipSummaryDto>> GetByUniverseAsync(int universeId)
    {
        var championships = await _context.Championships
            .Where(c => c.UniverseId == universeId)
            .Include(c => c.Format)
            .Include(c => c.ChampionshipTeams)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
            .ToListAsync();

        return championships.Select(c =>
        {
            var (status, currentRound, totalRounds) = ComputeProgress(c);
            return new ChampionshipSummaryDto
            {
                Id = c.Id,
                Name = c.Name,
                Format = c.Format.Type,
                Status = status,
                Teams = c.ChampionshipTeams.Count,
                CurrentRound = currentRound,
                TotalRounds = totalRounds
            };
        }).ToList();
    }

    public async Task<ChampionshipDetailDto> GetByIdAsync(int id)
    {
        var championship = await _context.Championships
            .Include(c => c.Universe)
            .Include(c => c.Format)
            .Include(c => c.ChampionshipTeams)
                .ThenInclude(ct => ct.Team)
            .Include(c => c.ChampionshipRules)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.HomeTeam)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.AwayTeam)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Groups)
                    .ThenInclude(g => g.GroupTeams)
                        .ThenInclude(gt => gt.Team)
            .FirstOrDefaultAsync(c => c.Id == id);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        var (status, currentRound, totalRounds) = ComputeProgress(championship);

        return new ChampionshipDetailDto
        {
            Id = championship.Id,
            Name = championship.Name,
            Slug = championship.Slug,
            Universe = new UniverseSummaryDto
            {
                Id = championship.Universe.Id,
                Name = championship.Universe.Name
            },
            Format = championship.Format.Type,
            Status = status,
            CurrentRound = currentRound,
            TotalRounds = totalRounds,
            Teams = championship.ChampionshipTeams
                .Select(ct => new TeamSummaryDto { Id = ct.Team.Id, Name = ct.Team.Name })
                .OrderBy(t => t.Name)
                .ToList(),
            Standings = championship.Format.Type == "round_robin" ? BuildStandings(championship) : new(),
            Groups = championship.Format.Type == "groups_knockout" ? BuildGroupStandings(championship) : new(),
            Rounds = BuildRounds(championship)
        };
    }

    /// <summary>
    /// Returns the knockout bracket (single/double elimination, or the knockout phase of groups_knockout)
    /// as rounds of matches, with each match's teams, score, winner, and the match its winner feeds into.
    /// </summary>
    public async Task<BracketDto> GetBracketAsync(int championshipId)
    {
        var championship = await _context.Championships
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.HomeTeam)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.AwayTeam)
            .FirstOrDefaultAsync(c => c.Id == championshipId);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        var knockoutPhase = championship.Phases.FirstOrDefault(p => p.Type == "knockout");
        if (knockoutPhase == null)
            throw new BadRequestException("Este campeonato não possui fase de mata-mata");

        var matches = knockoutPhase.Rounds.SelectMany(r => r.Matches).ToList();

        // Map each match to the match its winner advances into, so the frontend can draw the connectors.
        var nextByWinner = new Dictionary<int, int>();
        foreach (var match in matches)
        {
            if (match.HomeSourceMatchId is int homeSource && match.HomeSourceOutcome == KnockoutEngine.Winner)
                nextByWinner[homeSource] = match.Id;
            if (match.AwaySourceMatchId is int awaySource && match.AwaySourceOutcome == KnockoutEngine.Winner)
                nextByWinner[awaySource] = match.Id;
        }

        var bracket = new BracketDto();
        foreach (var round in knockoutPhase.Rounds.OrderBy(r => r.Number).ThenBy(r => r.Bracket))
        {
            var bracketRound = new BracketRoundDto
            {
                Name = round.Name ?? $"Rodada {round.Number}",
                Bracket = round.Bracket
            };

            int position = 1;
            foreach (var match in round.Matches.OrderBy(m => m.Id))
            {
                bracketRound.Matches.Add(new BracketMatchDto
                {
                    Id = match.Id,
                    Position = position++,
                    HomeTeam = ToBracketTeam(match.HomeTeam, match.Status, match.HomeGoals),
                    AwayTeam = ToBracketTeam(match.AwayTeam, match.Status, match.AwayGoals),
                    WinnerId = KnockoutEngine.WinnerOrNull(match),
                    Status = match.Status,
                    NextMatchId = nextByWinner.TryGetValue(match.Id, out var next) ? next : null
                });
            }

            bracket.Rounds.Add(bracketRound);
        }

        return bracket;
    }

    /// <summary>
    /// Aggregates a championship's statistics from its finished matches. Player metrics are derived from
    /// the team each player controls (PlayerChampionship) — there are no per-player events, so MostAssists
    /// and BiggestComeback are left empty (no assist data; comebacks need in-match progression we don't store).
    /// </summary>
    public async Task<ChampionshipStatisticsDto> GetStatisticsAsync(int championshipId)
    {
        var championship = await _context.Championships
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.HomeTeam)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.AwayTeam)
            .Include(c => c.ChampionshipTeams)
                .ThenInclude(ct => ct.Team)
            .FirstOrDefaultAsync(c => c.Id == championshipId);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        var teamNames = championship.ChampionshipTeams.ToDictionary(ct => ct.Team.Id, ct => ct.Team.Name);

        // teamId -> player controlling that team in this championship (one player controls one full team)
        var teamToPlayer = (await _context.PlayerChampionships
                .Where(pc => pc.ChampionshipId == championshipId && pc.TeamId != null && pc.Player.IsActive)
                .Select(pc => new { TeamId = pc.TeamId!.Value, pc.PlayerId, PlayerName = pc.Player.Name })
                .ToListAsync())
            .ToDictionary(e => e.TeamId, e => (e.PlayerId, e.PlayerName));

        var matches = championship.Phases
            .SelectMany(p => p.Rounds)
            .SelectMany(r => r.Matches)
            .Where(m => m.Status == "finished" && m.HomeTeamId != null && m.AwayTeamId != null)
            .ToList();

        var stats = new ChampionshipStatisticsDto();
        if (matches.Count == 0)
            return stats;

        // Player goals (via the controlled team), team wins, goals conceded per team.
        var playerGoals = new Dictionary<int, PlayerGoalStatDto>();
        var teamWins = teamNames.Keys.ToDictionary(id => id, _ => 0);
        var conceded = teamNames.Keys.ToDictionary(id => id, _ => (Conceded: 0, Played: 0));

        void AddPlayerGoals(int teamId, int goals)
        {
            if (!teamToPlayer.TryGetValue(teamId, out var player))
                return;
            if (playerGoals.TryGetValue(player.PlayerId, out var row))
                row.Goals += goals;
            else
                playerGoals[player.PlayerId] = new PlayerGoalStatDto
                {
                    PlayerId = player.PlayerId,
                    Name = player.PlayerName,
                    Team = teamNames.GetValueOrDefault(teamId, string.Empty),
                    Goals = goals
                };
        }

        void AddConceded(int teamId, int goalsAgainst)
        {
            if (!conceded.TryGetValue(teamId, out var c))
                return;
            conceded[teamId] = (c.Conceded + goalsAgainst, c.Played + 1);
        }

        int totalGoals = 0;
        foreach (var match in matches)
        {
            int home = match.HomeTeamId!.Value, away = match.AwayTeamId!.Value;
            totalGoals += match.HomeGoals + match.AwayGoals;

            AddPlayerGoals(home, match.HomeGoals);
            AddPlayerGoals(away, match.AwayGoals);
            AddConceded(home, match.AwayGoals);
            AddConceded(away, match.HomeGoals);

            if (match.HomeGoals > match.AwayGoals && teamWins.ContainsKey(home)) teamWins[home]++;
            else if (match.AwayGoals > match.HomeGoals && teamWins.ContainsKey(away)) teamWins[away]++;
        }

        // Top scorers (players ranked by the goals of the team they control).
        stats.TopScorers = playerGoals.Values
            .OrderByDescending(p => p.Goals)
            .ThenBy(p => p.Name)
            .Take(10)
            .ToList();
        stats.TopScorer = stats.TopScorers.FirstOrDefault() ?? new PlayerGoalStatDto();

        // Most wins.
        var topTeam = teamWins.Where(kv => kv.Value > 0).OrderByDescending(kv => kv.Value).ThenBy(kv => teamNames.GetValueOrDefault(kv.Key)).FirstOrDefault();
        if (topTeam.Value > 0)
            stats.MostWins = new TeamWinsDto { TeamId = topTeam.Key, Name = teamNames.GetValueOrDefault(topTeam.Key, string.Empty), Wins = topTeam.Value };

        // Biggest win (largest goal margin among decisive results).
        var biggest = matches
            .Where(m => m.HomeGoals != m.AwayGoals)
            .OrderByDescending(m => Math.Abs(m.HomeGoals - m.AwayGoals))
            .ThenByDescending(m => m.HomeGoals + m.AwayGoals)
            .FirstOrDefault();
        if (biggest != null)
            stats.BiggestWin = new MatchScoreDto
            {
                MatchId = biggest.Id,
                HomeTeam = biggest.HomeTeam?.Name ?? string.Empty,
                AwayTeam = biggest.AwayTeam?.Name ?? string.Empty,
                HomeGoals = biggest.HomeGoals,
                AwayGoals = biggest.AwayGoals
            };

        // Goals per match (across the whole championship).
        stats.GoalsPerMatch = Math.Round((double)totalGoals / matches.Count, 2);

        // Best/worst defence by average goals conceded per match played.
        var defences = conceded
            .Where(kv => kv.Value.Played > 0)
            .Select(kv => new TeamAverageDto
            {
                TeamId = kv.Key,
                Name = teamNames.GetValueOrDefault(kv.Key, string.Empty),
                Average = Math.Round((double)kv.Value.Conceded / kv.Value.Played, 2)
            })
            .ToList();
        if (defences.Count > 0)
        {
            stats.GoalsConcededPerMatch = new GoalsConcededPerMatchDto
            {
                Best = defences.OrderBy(d => d.Average).ThenBy(d => d.Name).First(),
                Worst = defences.OrderByDescending(d => d.Average).ThenBy(d => d.Name).First()
            };
        }

        // MostAssists / BiggestComeback intentionally left empty — no assist events and no in-match
        // progression are stored (1 player = 1 team, only the final score is recorded).
        return stats;
    }

    private static BracketTeamDto? ToBracketTeam(Team? team, string status, int goals)
    {
        if (team == null)
            return null;
        return new BracketTeamDto
        {
            Id = team.Id,
            Name = team.Name,
            Goals = status == "scheduled" ? null : goals
        };
    }

    public async Task UpdateAsync(int id, UpdateChampionshipDto dto)
    {
        var championship = await _context.Championships.FindAsync(id);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        await _authorizer.RequireRoleAsync(championship.UniverseId, UniverseRole.Admin);

        if (championship.Name != dto.Name)
            championship.Slug = await GenerateUniqueSlugAsync(dto.Name, championship.UniverseId, id);

        championship.Name = dto.Name;
        championship.Distribution = dto.Distribution;

        await _context.SaveChangesAsync();
    }

    public async Task DeleteAsync(int id)
    {
        var championship = await _context.Championships.FindAsync(id);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        await _authorizer.RequireRoleAsync(championship.UniverseId, UniverseRole.Admin);

        // Cascade delete removes phases, rounds, matches, team links, rules and enrollments.
        _context.Championships.Remove(championship);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Team pool management (ChampionshipTeam)
    // ---------------------------------------------------------------------

    public async Task<List<TeamSummaryDto>> GetTeamsAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        return await _context.ChampionshipTeams
            .Where(ct => ct.ChampionshipId == championshipId)
            .Select(ct => new TeamSummaryDto { Id = ct.Team.Id, Name = ct.Team.Name })
            .OrderBy(t => t.Name)
            .ToListAsync();
    }

    public async Task AddTeamAsync(int championshipId, AddChampionshipTeamDto dto)
    {
        var championship = await _context.Championships.FindAsync(championshipId);
        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        await _authorizer.RequireRoleAsync(championship.UniverseId, UniverseRole.Admin);

        await EnsurePoolEditableAsync(championshipId);

        int teamId;

        if (dto.TeamId.HasValue)
        {
            var team = await _context.Teams.FindAsync(dto.TeamId.Value);
            if (team == null)
                throw new NotFoundException("Time não encontrado");
            if (team.UniverseId != championship.UniverseId)
                throw new BadRequestException("O time não pertence ao universo deste campeonato");

            teamId = team.Id;
        }
        else if (!string.IsNullOrWhiteSpace(dto.Name))
        {
            var existing = await _context.Teams
                .FirstOrDefaultAsync(t => t.UniverseId == championship.UniverseId && t.Name == dto.Name);

            if (existing != null)
            {
                teamId = existing.Id;
            }
            else
            {
                var team = new Team { Name = dto.Name, UniverseId = championship.UniverseId };
                _context.Teams.Add(team);
                await _context.SaveChangesAsync();
                teamId = team.Id;
            }
        }
        else
        {
            throw new BadRequestException("Informe o id de um time existente ou o nome de um novo time");
        }

        var alreadyAdded = await _context.ChampionshipTeams
            .AnyAsync(ct => ct.ChampionshipId == championshipId && ct.TeamId == teamId);
        if (alreadyAdded)
            throw new ConflictException("Este time já está neste campeonato");

        _context.ChampionshipTeams.Add(new ChampionshipTeam
        {
            ChampionshipId = championshipId,
            TeamId = teamId
        });
        await _context.SaveChangesAsync();
    }

    public async Task RemoveTeamAsync(int championshipId, int teamId)
    {
        await RequireChampionshipAdminAsync(championshipId);

        var link = await _context.ChampionshipTeams
            .FirstOrDefaultAsync(ct => ct.ChampionshipId == championshipId && ct.TeamId == teamId);

        if (link == null)
            throw new NotFoundException("Time não encontrado neste campeonato");

        await EnsurePoolEditableAsync(championshipId);

        var assignedToPlayer = await _context.PlayerChampionships
            .AnyAsync(pc => pc.ChampionshipId == championshipId && pc.TeamId == teamId);
        if (assignedToPlayer)
            throw new ConflictException("Não é possível remover um time atribuído a um jogador neste campeonato");

        var hasMatches = await _context.Matches
            .AnyAsync(m => (m.HomeTeamId == teamId || m.AwayTeamId == teamId)
                && m.Round.Phase.ChampionshipId == championshipId);
        if (hasMatches)
            throw new ConflictException("Não é possível remover um time que já possui partidas neste campeonato");

        _context.ChampionshipTeams.Remove(link);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Rules (ChampionshipRule)
    // ---------------------------------------------------------------------

    public async Task<List<ChampionshipRuleDto>> GetRulesAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        return await _context.ChampionshipRules
            .Where(r => r.ChampionshipId == championshipId)
            .Select(r => new ChampionshipRuleDto { Key = r.Key, Value = r.Value })
            .ToListAsync();
    }

    /// <summary>
    /// Creates or updates a rule (upsert by key) for the championship.
    /// </summary>
    public async Task SetRuleAsync(int championshipId, ChampionshipRuleDto dto)
    {
        await RequireChampionshipAdminAsync(championshipId);

        var rule = await _context.ChampionshipRules
            .FirstOrDefaultAsync(r => r.ChampionshipId == championshipId && r.Key == dto.Key);

        if (rule == null)
        {
            _context.ChampionshipRules.Add(new ChampionshipRule
            {
                ChampionshipId = championshipId,
                Key = dto.Key,
                Value = dto.Value
            });
        }
        else
        {
            rule.Value = dto.Value;
        }

        await _context.SaveChangesAsync();
    }

    public async Task RemoveRuleAsync(int championshipId, string key)
    {
        await RequireChampionshipAdminAsync(championshipId);

        var rule = await _context.ChampionshipRules
            .FirstOrDefaultAsync(r => r.ChampionshipId == championshipId && r.Key == key);

        if (rule == null)
            throw new NotFoundException("Regra não encontrada");

        _context.ChampionshipRules.Remove(rule);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Player enrollments (PlayerChampionship)
    // ---------------------------------------------------------------------

    public async Task<List<ChampionshipPlayerDto>> GetPlayersAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        return await _context.PlayerChampionships
            .Where(pc => pc.ChampionshipId == championshipId)
            .Select(pc => new ChampionshipPlayerDto
            {
                PlayerId = pc.PlayerId,
                PlayerName = pc.Player.Name,
                TeamId = pc.TeamId,
                TeamName = pc.Team != null ? pc.Team.Name : null
            })
            .OrderBy(p => p.PlayerName)
            .ToListAsync();
    }

    /// <summary>
    /// Enrolls a player in the championship. When a team is provided the assignment is manual and must be
    /// a team from the championship pool not already taken by another player (one player controls one team).
    /// </summary>
    public async Task EnrollPlayerAsync(int championshipId, EnrollPlayerDto dto)
    {
        var championship = await _context.Championships.FindAsync(championshipId);
        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        await _authorizer.RequireRoleAsync(championship.UniverseId, UniverseRole.Admin);

        var player = await _context.Players
            .FirstOrDefaultAsync(p => p.Id == dto.PlayerId && p.IsActive);
        if (player == null)
            throw new NotFoundException("Jogador não encontrado");
        if (player.UniverseId != championship.UniverseId)
            throw new BadRequestException("O jogador não pertence ao universo deste campeonato");

        var alreadyEnrolled = await _context.PlayerChampionships
            .AnyAsync(pc => pc.ChampionshipId == championshipId && pc.PlayerId == dto.PlayerId);
        if (alreadyEnrolled)
            throw new ConflictException("O jogador já está inscrito neste campeonato");

        if (dto.TeamId.HasValue)
            await EnsureTeamAssignableAsync(championshipId, dto.TeamId.Value, null);

        _context.PlayerChampionships.Add(new PlayerChampionship
        {
            ChampionshipId = championshipId,
            PlayerId = dto.PlayerId,
            TeamId = dto.TeamId
        });
        await _context.SaveChangesAsync();
    }

    /// <summary>
    /// Manually assigns or reassigns a team to an enrolled player.
    /// </summary>
    public async Task AssignTeamAsync(int championshipId, int playerId, AssignPlayerTeamDto dto)
    {
        await RequireChampionshipAdminAsync(championshipId);

        var enrollment = await _context.PlayerChampionships
            .FirstOrDefaultAsync(pc => pc.ChampionshipId == championshipId && pc.PlayerId == playerId);

        if (enrollment == null)
            throw new NotFoundException("Jogador não está inscrito neste campeonato");

        await EnsureTeamAssignableAsync(championshipId, dto.TeamId, playerId);

        enrollment.TeamId = dto.TeamId;
        await _context.SaveChangesAsync();
    }

    /// <summary>
    /// Randomly draws teams from the championship pool to enrolled players that do not yet have a team,
    /// preserving any manual assignments. Each player gets a distinct team (one player = one team).
    /// </summary>
    public async Task<List<ChampionshipPlayerDto>> DrawTeamsAsync(int championshipId)
    {
        await RequireChampionshipAdminAsync(championshipId);

        var enrollments = await _context.PlayerChampionships
            .Where(pc => pc.ChampionshipId == championshipId)
            .Include(pc => pc.Player)
            .ToListAsync();

        if (enrollments.Count == 0)
            throw new BadRequestException("Não há jogadores inscritos para sortear");

        var poolTeamIds = await _context.ChampionshipTeams
            .Where(ct => ct.ChampionshipId == championshipId)
            .Select(ct => ct.TeamId)
            .ToListAsync();

        var takenTeamIds = enrollments
            .Where(e => e.TeamId.HasValue)
            .Select(e => e.TeamId!.Value)
            .ToHashSet();

        var playersWithoutTeam = enrollments.Where(e => !e.TeamId.HasValue).ToList();
        var availableTeamIds = poolTeamIds.Where(t => !takenTeamIds.Contains(t)).ToList();

        if (playersWithoutTeam.Count > availableTeamIds.Count)
            throw new ConflictException("Não há times suficientes no campeonato para sortear todos os jogadores");

        var shuffled = availableTeamIds.OrderBy(_ => Guid.NewGuid()).ToList();
        for (int i = 0; i < playersWithoutTeam.Count; i++)
            playersWithoutTeam[i].TeamId = shuffled[i];

        await _context.SaveChangesAsync();

        return await GetPlayersAsync(championshipId);
    }

    public async Task RemovePlayerAsync(int championshipId, int playerId)
    {
        await RequireChampionshipAdminAsync(championshipId);

        var enrollment = await _context.PlayerChampionships
            .FirstOrDefaultAsync(pc => pc.ChampionshipId == championshipId && pc.PlayerId == playerId);

        if (enrollment == null)
            throw new NotFoundException("Jogador não está inscrito neste campeonato");

        _context.PlayerChampionships.Remove(enrollment);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------

    private async Task EnsureChampionshipExistsAsync(int championshipId)
    {
        var exists = await _context.Championships.AnyAsync(c => c.Id == championshipId);
        if (!exists)
            throw new NotFoundException("Campeonato não encontrado");
    }

    /// <summary>
    /// Blocks changes to the team pool once any match of the championship is ongoing or finished.
    /// </summary>
    private async Task EnsurePoolEditableAsync(int championshipId)
    {
        var locked = await _context.Matches
            .AnyAsync(m => m.Round.Phase.ChampionshipId == championshipId && m.Status != "scheduled");
        if (locked)
            throw new ConflictException("O pool de times não pode ser alterado: já há partidas em andamento ou finalizadas");
    }

    /// <summary>
    /// Validates that a team belongs to the championship pool and is not already assigned to a different player.
    /// </summary>
    private async Task EnsureTeamAssignableAsync(int championshipId, int teamId, int? currentPlayerId)
    {
        var inPool = await _context.ChampionshipTeams
            .AnyAsync(ct => ct.ChampionshipId == championshipId && ct.TeamId == teamId);
        if (!inPool)
            throw new BadRequestException("O time não faz parte deste campeonato");

        var taken = await _context.PlayerChampionships
            .AnyAsync(pc => pc.ChampionshipId == championshipId
                && pc.TeamId == teamId
                && pc.PlayerId != currentPlayerId);
        if (taken)
            throw new ConflictException("Este time já está atribuído a outro jogador neste campeonato");
    }

    private async Task<string> GenerateUniqueSlugAsync(string name, int universeId, int? excludeId = null)
    {
        var baseSlug = Slugify(name);
        if (string.IsNullOrEmpty(baseSlug))
            baseSlug = "campeonato";

        var slug = baseSlug;
        var suffix = 2;

        while (await _context.Championships.AnyAsync(c =>
            c.UniverseId == universeId && c.Slug == slug && c.Id != excludeId))
        {
            slug = $"{baseSlug}-{suffix}";
            suffix++;
        }

        return slug;
    }

    private static string Slugify(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        var normalized = value.Trim().ToLowerInvariant().Normalize(NormalizationForm.FormD);
        var builder = new StringBuilder();

        foreach (var c in normalized)
        {
            var category = CharUnicodeInfo.GetUnicodeCategory(c);
            if (category == UnicodeCategory.NonSpacingMark)
                continue;

            if (char.IsLetterOrDigit(c))
                builder.Append(c);
            else if (c is ' ' or '-' or '_')
                builder.Append('-');
        }

        var slug = builder.ToString();
        while (slug.Contains("--"))
            slug = slug.Replace("--", "-");

        return slug.Trim('-');
    }

    /// <summary>
    /// Derives the championship status and round progress from its matches (no persisted status column).
    /// </summary>
    private static (string Status, int CurrentRound, int TotalRounds) ComputeProgress(Championship championship)
    {
        var rounds = championship.Phases
            .SelectMany(p => p.Rounds)
            .ToList();

        var totalRounds = rounds.Count;
        var matches = rounds.SelectMany(r => r.Matches).ToList();

        if (matches.Count == 0)
            return ("draft", 0, totalRounds);

        var allFinished = matches.All(m => m.Status == "finished");
        var status = allFinished ? "finished" : "ongoing";

        var currentRound = rounds
            .Where(r => r.Matches.Any(m => m.Status == "finished" || m.Status == "ongoing"))
            .Select(r => r.Number)
            .DefaultIfEmpty(0)
            .Max();

        return (status, currentRound, totalRounds);
    }

    private List<StandingsRowDto> BuildStandings(Championship championship)
    {
        var winPoints = GetIntRule(championship, "win_points", DefaultWinPoints);
        var drawPoints = GetIntRule(championship, "draw_points", DefaultDrawPoints);

        var roster = championship.ChampionshipTeams.ToDictionary(ct => ct.Team.Id, ct => ct.Team.Name);
        var matches = championship.Phases.SelectMany(p => p.Rounds).SelectMany(r => r.Matches);

        return ComputeTable(roster, matches, winPoints, drawPoints);
    }

    /// <summary>Builds one standings table per group, from each group's own matches (groups_knockout).</summary>
    private List<GroupStandingsDto> BuildGroupStandings(Championship championship)
    {
        var winPoints = GetIntRule(championship, "win_points", DefaultWinPoints);
        var drawPoints = GetIntRule(championship, "draw_points", DefaultDrawPoints);

        var allMatches = championship.Phases.SelectMany(p => p.Rounds).SelectMany(r => r.Matches).ToList();

        return championship.Phases
            .Where(p => p.Type == "groups")
            .SelectMany(p => p.Groups)
            .OrderBy(g => g.Name)
            .Select(group => new GroupStandingsDto
            {
                Group = group.Name,
                Standings = ComputeTable(
                    group.GroupTeams.ToDictionary(gt => gt.Team.Id, gt => gt.Team.Name),
                    allMatches.Where(m => m.GroupId == group.Id),
                    winPoints,
                    drawPoints)
            })
            .ToList();
    }

    /// <summary>
    /// Builds a standings table for a roster (team id → name) from its finished matches. Order: points,
    /// goal difference, goals for, then team name as a deterministic final tiebreak.
    /// </summary>
    private static List<StandingsRowDto> ComputeTable(
        Dictionary<int, string> roster, IEnumerable<Match> matches, int winPoints, int drawPoints)
    {
        var rows = roster.ToDictionary(kv => kv.Key, kv => new StandingsRowDto { Team = kv.Value });

        foreach (var match in matches.Where(m => m.Status == "finished"))
        {
            if (match.HomeTeamId is not int homeId || match.AwayTeamId is not int awayId)
                continue;
            if (!rows.TryGetValue(homeId, out var home) || !rows.TryGetValue(awayId, out var away))
                continue;

            home.Played++;
            away.Played++;
            home.GoalsFor += match.HomeGoals;
            home.GoalsAgainst += match.AwayGoals;
            away.GoalsFor += match.AwayGoals;
            away.GoalsAgainst += match.HomeGoals;

            if (match.HomeGoals > match.AwayGoals)
            {
                home.Wins++;
                away.Losses++;
                home.Points += winPoints;
            }
            else if (match.HomeGoals < match.AwayGoals)
            {
                away.Wins++;
                home.Losses++;
                away.Points += winPoints;
            }
            else
            {
                home.Draws++;
                away.Draws++;
                home.Points += drawPoints;
                away.Points += drawPoints;
            }
        }

        var ordered = rows.Values
            .Select(r =>
            {
                r.GoalDifference = r.GoalsFor - r.GoalsAgainst;
                return r;
            })
            .OrderByDescending(r => r.Points)
            .ThenByDescending(r => r.GoalDifference)
            .ThenByDescending(r => r.GoalsFor)
            .ThenBy(r => r.Team)
            .ToList();

        for (int i = 0; i < ordered.Count; i++)
            ordered[i].Position = i + 1;

        return ordered;
    }

    private static List<RoundSummaryDto> BuildRounds(Championship championship)
    {
        return championship.Phases
            .OrderBy(p => p.Order)
            .SelectMany(p => p.Rounds.OrderBy(r => r.Number))
            .Select(r => new RoundSummaryDto
            {
                Number = r.Number,
                Name = r.Name,
                Status = RoundStatus(r),
                Matches = r.Matches.Select(m => new MatchSummaryDto
                {
                    Id = m.Id,
                    HomeTeam = m.HomeTeam != null ? m.HomeTeam.Name : null,
                    AwayTeam = m.AwayTeam != null ? m.AwayTeam.Name : null,
                    HomeGoals = m.Status == "scheduled" ? null : m.HomeGoals,
                    AwayGoals = m.Status == "scheduled" ? null : m.AwayGoals,
                    HomePenalties = m.HomePenalties,
                    AwayPenalties = m.AwayPenalties,
                    Status = m.Status,
                    Date = m.Date
                }).ToList()
            })
            .ToList();
    }

    private static string RoundStatus(Round round)
    {
        if (round.Matches.Count == 0)
            return "scheduled";
        if (round.Matches.All(m => m.Status == "finished"))
            return "finished";
        if (round.Matches.Any(m => m.Status is "finished" or "ongoing"))
            return "ongoing";
        return "scheduled";
    }

    private static int GetIntRule(Championship championship, string key, int fallback)
    {
        var rule = championship.ChampionshipRules.FirstOrDefault(r => r.Key == key);
        return rule != null && int.TryParse(rule.Value, out var parsed) ? parsed : fallback;
    }
}
