using System.Globalization;
using System.Text;
using Microsoft.EntityFrameworkCore;
using MyCup.Data;
using MyCup.DTOs.Championships;
using MyCup.DTOs.Common;
using MyCup.DTOs.Teams;
using MyCup.Errors;
using MyCup.Models;

namespace MyCup.Services;

/// <summary>
/// Service responsible for championship business rules. The championship is an aggregate root that also
/// manages its team pool, rules, and player enrollments (PlayerChampionship). Phases/rounds/matches are
/// generated by the fixture engine (BE-008) and only read here for status/standings.
/// </summary>
public class ChampionshipsService
{
    private const int DefaultWinPoints = 3;
    private const int DefaultDrawPoints = 1;

    private readonly AppDbContext _context;

    public ChampionshipsService(AppDbContext context)
    {
        _context = context;
    }

    // ---------------------------------------------------------------------
    // Championship CRUD
    // ---------------------------------------------------------------------

    public async Task<int> CreateChampionshipAsync(CreateChampionshipDto dto)
    {
        var universeExists = await _context.Universes.AnyAsync(u => u.Id == dto.UniverseId);
        if (!universeExists)
            throw new NotFoundException("Universo não encontrado");

        var formatExists = await _context.Formats.AnyAsync(f => f.Id == dto.FormatId);
        if (!formatExists)
            throw new NotFoundException("Formato não encontrado");

        Championship championship = new()
        {
            Name = dto.Name,
            UniverseId = dto.UniverseId,
            FormatId = dto.FormatId,
            Distribution = dto.Distribution,
            Slug = await GenerateUniqueSlugAsync(dto.Name, dto.UniverseId)
        };

        _context.Championships.Add(championship);
        await _context.SaveChangesAsync();

        return championship.Id;
    }

    public async Task<List<ChampionshipSummaryDto>> GetByUniverseAsync(int universeId)
    {
        var championships = await _context.Championships
            .Where(c => c.UniverseId == universeId)
            .Include(c => c.Format)
            .Include(c => c.ChampionshipTeams)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
            .ToListAsync();

        return championships.Select(c =>
        {
            var (status, currentRound, totalRounds) = ComputeProgress(c);
            return new ChampionshipSummaryDto
            {
                Id = c.Id,
                Name = c.Name,
                Format = c.Format.Type,
                Status = status,
                Teams = c.ChampionshipTeams.Count,
                CurrentRound = currentRound,
                TotalRounds = totalRounds
            };
        }).ToList();
    }

    public async Task<ChampionshipDetailDto> GetByIdAsync(int id)
    {
        var championship = await _context.Championships
            .Include(c => c.Universe)
            .Include(c => c.Format)
            .Include(c => c.ChampionshipTeams)
                .ThenInclude(ct => ct.Team)
            .Include(c => c.ChampionshipRules)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.HomeTeam)
            .Include(c => c.Phases)
                .ThenInclude(p => p.Rounds)
                    .ThenInclude(r => r.Matches)
                        .ThenInclude(m => m.AwayTeam)
            .FirstOrDefaultAsync(c => c.Id == id);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        var (status, currentRound, totalRounds) = ComputeProgress(championship);

        return new ChampionshipDetailDto
        {
            Id = championship.Id,
            Name = championship.Name,
            Slug = championship.Slug,
            Universe = new UniverseSummaryDto
            {
                Id = championship.Universe.Id,
                Name = championship.Universe.Name
            },
            Format = championship.Format.Type,
            Status = status,
            CurrentRound = currentRound,
            TotalRounds = totalRounds,
            Teams = championship.ChampionshipTeams
                .Select(ct => new TeamSummaryDto { Id = ct.Team.Id, Name = ct.Team.Name })
                .OrderBy(t => t.Name)
                .ToList(),
            Standings = BuildStandings(championship),
            Rounds = BuildRounds(championship)
        };
    }

    public async Task UpdateAsync(int id, UpdateChampionshipDto dto)
    {
        var championship = await _context.Championships.FindAsync(id);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        if (championship.Name != dto.Name)
            championship.Slug = await GenerateUniqueSlugAsync(dto.Name, championship.UniverseId, id);

        championship.Name = dto.Name;
        championship.Distribution = dto.Distribution;

        await _context.SaveChangesAsync();
    }

    public async Task DeleteAsync(int id)
    {
        var championship = await _context.Championships.FindAsync(id);

        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        // Cascade delete removes phases, rounds, matches, team links, rules and enrollments.
        _context.Championships.Remove(championship);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Team pool management (ChampionshipTeam)
    // ---------------------------------------------------------------------

    public async Task<List<TeamSummaryDto>> GetTeamsAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        return await _context.ChampionshipTeams
            .Where(ct => ct.ChampionshipId == championshipId)
            .Select(ct => new TeamSummaryDto { Id = ct.Team.Id, Name = ct.Team.Name })
            .OrderBy(t => t.Name)
            .ToListAsync();
    }

    public async Task AddTeamAsync(int championshipId, AddChampionshipTeamDto dto)
    {
        var championship = await _context.Championships.FindAsync(championshipId);
        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        int teamId;

        if (dto.TeamId.HasValue)
        {
            var team = await _context.Teams.FindAsync(dto.TeamId.Value);
            if (team == null)
                throw new NotFoundException("Time não encontrado");
            if (team.UniverseId != championship.UniverseId)
                throw new BadRequestException("O time não pertence ao universo deste campeonato");

            teamId = team.Id;
        }
        else if (!string.IsNullOrWhiteSpace(dto.Name))
        {
            var existing = await _context.Teams
                .FirstOrDefaultAsync(t => t.UniverseId == championship.UniverseId && t.Name == dto.Name);

            if (existing != null)
            {
                teamId = existing.Id;
            }
            else
            {
                var team = new Team { Name = dto.Name, UniverseId = championship.UniverseId };
                _context.Teams.Add(team);
                await _context.SaveChangesAsync();
                teamId = team.Id;
            }
        }
        else
        {
            throw new BadRequestException("Informe o id de um time existente ou o nome de um novo time");
        }

        var alreadyAdded = await _context.ChampionshipTeams
            .AnyAsync(ct => ct.ChampionshipId == championshipId && ct.TeamId == teamId);
        if (alreadyAdded)
            throw new ConflictException("Este time já está neste campeonato");

        _context.ChampionshipTeams.Add(new ChampionshipTeam
        {
            ChampionshipId = championshipId,
            TeamId = teamId
        });
        await _context.SaveChangesAsync();
    }

    public async Task RemoveTeamAsync(int championshipId, int teamId)
    {
        var link = await _context.ChampionshipTeams
            .FirstOrDefaultAsync(ct => ct.ChampionshipId == championshipId && ct.TeamId == teamId);

        if (link == null)
            throw new NotFoundException("Time não encontrado neste campeonato");

        var assignedToPlayer = await _context.PlayerChampionships
            .AnyAsync(pc => pc.ChampionshipId == championshipId && pc.TeamId == teamId);
        if (assignedToPlayer)
            throw new ConflictException("Não é possível remover um time atribuído a um jogador neste campeonato");

        var hasMatches = await _context.Matches
            .AnyAsync(m => (m.HomeTeamId == teamId || m.AwayTeamId == teamId)
                && m.Round.Phase.ChampionshipId == championshipId);
        if (hasMatches)
            throw new ConflictException("Não é possível remover um time que já possui partidas neste campeonato");

        _context.ChampionshipTeams.Remove(link);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Rules (ChampionshipRule)
    // ---------------------------------------------------------------------

    public async Task<List<ChampionshipRuleDto>> GetRulesAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        return await _context.ChampionshipRules
            .Where(r => r.ChampionshipId == championshipId)
            .Select(r => new ChampionshipRuleDto { Key = r.Key, Value = r.Value })
            .ToListAsync();
    }

    /// <summary>
    /// Creates or updates a rule (upsert by key) for the championship.
    /// </summary>
    public async Task SetRuleAsync(int championshipId, ChampionshipRuleDto dto)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        var rule = await _context.ChampionshipRules
            .FirstOrDefaultAsync(r => r.ChampionshipId == championshipId && r.Key == dto.Key);

        if (rule == null)
        {
            _context.ChampionshipRules.Add(new ChampionshipRule
            {
                ChampionshipId = championshipId,
                Key = dto.Key,
                Value = dto.Value
            });
        }
        else
        {
            rule.Value = dto.Value;
        }

        await _context.SaveChangesAsync();
    }

    public async Task RemoveRuleAsync(int championshipId, string key)
    {
        var rule = await _context.ChampionshipRules
            .FirstOrDefaultAsync(r => r.ChampionshipId == championshipId && r.Key == key);

        if (rule == null)
            throw new NotFoundException("Regra não encontrada");

        _context.ChampionshipRules.Remove(rule);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Player enrollments (PlayerChampionship)
    // ---------------------------------------------------------------------

    public async Task<List<ChampionshipPlayerDto>> GetPlayersAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        return await _context.PlayerChampionships
            .Where(pc => pc.ChampionshipId == championshipId)
            .Select(pc => new ChampionshipPlayerDto
            {
                PlayerId = pc.PlayerId,
                PlayerName = pc.Player.Name,
                TeamId = pc.TeamId,
                TeamName = pc.Team != null ? pc.Team.Name : null
            })
            .OrderBy(p => p.PlayerName)
            .ToListAsync();
    }

    /// <summary>
    /// Enrolls a player in the championship. When a team is provided the assignment is manual and must be
    /// a team from the championship pool not already taken by another player (one player controls one team).
    /// </summary>
    public async Task EnrollPlayerAsync(int championshipId, EnrollPlayerDto dto)
    {
        var championship = await _context.Championships.FindAsync(championshipId);
        if (championship == null)
            throw new NotFoundException("Campeonato não encontrado");

        var player = await _context.Players
            .FirstOrDefaultAsync(p => p.Id == dto.PlayerId && p.IsActive);
        if (player == null)
            throw new NotFoundException("Jogador não encontrado");
        if (player.UniverseId != championship.UniverseId)
            throw new BadRequestException("O jogador não pertence ao universo deste campeonato");

        var alreadyEnrolled = await _context.PlayerChampionships
            .AnyAsync(pc => pc.ChampionshipId == championshipId && pc.PlayerId == dto.PlayerId);
        if (alreadyEnrolled)
            throw new ConflictException("O jogador já está inscrito neste campeonato");

        if (dto.TeamId.HasValue)
            await EnsureTeamAssignableAsync(championshipId, dto.TeamId.Value, null);

        _context.PlayerChampionships.Add(new PlayerChampionship
        {
            ChampionshipId = championshipId,
            PlayerId = dto.PlayerId,
            TeamId = dto.TeamId
        });
        await _context.SaveChangesAsync();
    }

    /// <summary>
    /// Manually assigns or reassigns a team to an enrolled player.
    /// </summary>
    public async Task AssignTeamAsync(int championshipId, int playerId, AssignPlayerTeamDto dto)
    {
        var enrollment = await _context.PlayerChampionships
            .FirstOrDefaultAsync(pc => pc.ChampionshipId == championshipId && pc.PlayerId == playerId);

        if (enrollment == null)
            throw new NotFoundException("Jogador não está inscrito neste campeonato");

        await EnsureTeamAssignableAsync(championshipId, dto.TeamId, playerId);

        enrollment.TeamId = dto.TeamId;
        await _context.SaveChangesAsync();
    }

    /// <summary>
    /// Randomly draws teams from the championship pool to enrolled players that do not yet have a team,
    /// preserving any manual assignments. Each player gets a distinct team (one player = one team).
    /// </summary>
    public async Task<List<ChampionshipPlayerDto>> DrawTeamsAsync(int championshipId)
    {
        await EnsureChampionshipExistsAsync(championshipId);

        var enrollments = await _context.PlayerChampionships
            .Where(pc => pc.ChampionshipId == championshipId)
            .Include(pc => pc.Player)
            .ToListAsync();

        if (enrollments.Count == 0)
            throw new BadRequestException("Não há jogadores inscritos para sortear");

        var poolTeamIds = await _context.ChampionshipTeams
            .Where(ct => ct.ChampionshipId == championshipId)
            .Select(ct => ct.TeamId)
            .ToListAsync();

        var takenTeamIds = enrollments
            .Where(e => e.TeamId.HasValue)
            .Select(e => e.TeamId!.Value)
            .ToHashSet();

        var playersWithoutTeam = enrollments.Where(e => !e.TeamId.HasValue).ToList();
        var availableTeamIds = poolTeamIds.Where(t => !takenTeamIds.Contains(t)).ToList();

        if (playersWithoutTeam.Count > availableTeamIds.Count)
            throw new ConflictException("Não há times suficientes no campeonato para sortear todos os jogadores");

        var shuffled = availableTeamIds.OrderBy(_ => Guid.NewGuid()).ToList();
        for (int i = 0; i < playersWithoutTeam.Count; i++)
            playersWithoutTeam[i].TeamId = shuffled[i];

        await _context.SaveChangesAsync();

        return await GetPlayersAsync(championshipId);
    }

    public async Task RemovePlayerAsync(int championshipId, int playerId)
    {
        var enrollment = await _context.PlayerChampionships
            .FirstOrDefaultAsync(pc => pc.ChampionshipId == championshipId && pc.PlayerId == playerId);

        if (enrollment == null)
            throw new NotFoundException("Jogador não está inscrito neste campeonato");

        _context.PlayerChampionships.Remove(enrollment);
        await _context.SaveChangesAsync();
    }

    // ---------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------

    private async Task EnsureChampionshipExistsAsync(int championshipId)
    {
        var exists = await _context.Championships.AnyAsync(c => c.Id == championshipId);
        if (!exists)
            throw new NotFoundException("Campeonato não encontrado");
    }

    /// <summary>
    /// Validates that a team belongs to the championship pool and is not already assigned to a different player.
    /// </summary>
    private async Task EnsureTeamAssignableAsync(int championshipId, int teamId, int? currentPlayerId)
    {
        var inPool = await _context.ChampionshipTeams
            .AnyAsync(ct => ct.ChampionshipId == championshipId && ct.TeamId == teamId);
        if (!inPool)
            throw new BadRequestException("O time não faz parte deste campeonato");

        var taken = await _context.PlayerChampionships
            .AnyAsync(pc => pc.ChampionshipId == championshipId
                && pc.TeamId == teamId
                && pc.PlayerId != currentPlayerId);
        if (taken)
            throw new ConflictException("Este time já está atribuído a outro jogador neste campeonato");
    }

    private async Task<string> GenerateUniqueSlugAsync(string name, int universeId, int? excludeId = null)
    {
        var baseSlug = Slugify(name);
        if (string.IsNullOrEmpty(baseSlug))
            baseSlug = "campeonato";

        var slug = baseSlug;
        var suffix = 2;

        while (await _context.Championships.AnyAsync(c =>
            c.UniverseId == universeId && c.Slug == slug && c.Id != excludeId))
        {
            slug = $"{baseSlug}-{suffix}";
            suffix++;
        }

        return slug;
    }

    private static string Slugify(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        var normalized = value.Trim().ToLowerInvariant().Normalize(NormalizationForm.FormD);
        var builder = new StringBuilder();

        foreach (var c in normalized)
        {
            var category = CharUnicodeInfo.GetUnicodeCategory(c);
            if (category == UnicodeCategory.NonSpacingMark)
                continue;

            if (char.IsLetterOrDigit(c))
                builder.Append(c);
            else if (c is ' ' or '-' or '_')
                builder.Append('-');
        }

        var slug = builder.ToString();
        while (slug.Contains("--"))
            slug = slug.Replace("--", "-");

        return slug.Trim('-');
    }

    /// <summary>
    /// Derives the championship status and round progress from its matches (no persisted status column).
    /// </summary>
    private static (string Status, int CurrentRound, int TotalRounds) ComputeProgress(Championship championship)
    {
        var rounds = championship.Phases
            .SelectMany(p => p.Rounds)
            .ToList();

        var totalRounds = rounds.Count;
        var matches = rounds.SelectMany(r => r.Matches).ToList();

        if (matches.Count == 0)
            return ("draft", 0, totalRounds);

        var allFinished = matches.All(m => m.Status == "finished");
        var status = allFinished ? "finished" : "ongoing";

        var currentRound = rounds
            .Where(r => r.Matches.Any(m => m.Status == "finished" || m.Status == "ongoing"))
            .Select(r => r.Number)
            .DefaultIfEmpty(0)
            .Max();

        return (status, currentRound, totalRounds);
    }

    private List<StandingsRowDto> BuildStandings(Championship championship)
    {
        var winPoints = GetIntRule(championship, "win_points", DefaultWinPoints);
        var drawPoints = GetIntRule(championship, "draw_points", DefaultDrawPoints);

        var rows = championship.ChampionshipTeams.ToDictionary(
            ct => ct.Team.Id,
            ct => new StandingsRowDto { Team = ct.Team.Name });

        var finishedMatches = championship.Phases
            .SelectMany(p => p.Rounds)
            .SelectMany(r => r.Matches)
            .Where(m => m.Status == "finished");

        foreach (var match in finishedMatches)
        {
            if (!rows.TryGetValue(match.HomeTeamId, out var home) ||
                !rows.TryGetValue(match.AwayTeamId, out var away))
                continue;

            home.Played++;
            away.Played++;
            home.GoalsFor += match.HomeGoals;
            home.GoalsAgainst += match.AwayGoals;
            away.GoalsFor += match.AwayGoals;
            away.GoalsAgainst += match.HomeGoals;

            if (match.HomeGoals > match.AwayGoals)
            {
                home.Wins++;
                away.Losses++;
                home.Points += winPoints;
            }
            else if (match.HomeGoals < match.AwayGoals)
            {
                away.Wins++;
                home.Losses++;
                away.Points += winPoints;
            }
            else
            {
                home.Draws++;
                away.Draws++;
                home.Points += drawPoints;
                away.Points += drawPoints;
            }
        }

        var ordered = rows.Values
            .Select(r =>
            {
                r.GoalDifference = r.GoalsFor - r.GoalsAgainst;
                return r;
            })
            .OrderByDescending(r => r.Points)
            .ThenByDescending(r => r.GoalDifference)
            .ThenByDescending(r => r.GoalsFor)
            .ThenBy(r => r.Team)
            .ToList();

        for (int i = 0; i < ordered.Count; i++)
            ordered[i].Position = i + 1;

        return ordered;
    }

    private static List<RoundSummaryDto> BuildRounds(Championship championship)
    {
        return championship.Phases
            .OrderBy(p => p.Order)
            .SelectMany(p => p.Rounds.OrderBy(r => r.Number))
            .Select(r => new RoundSummaryDto
            {
                Number = r.Number,
                Name = r.Name,
                Status = RoundStatus(r),
                Matches = r.Matches.Select(m => new MatchSummaryDto
                {
                    Id = m.Id,
                    HomeTeam = m.HomeTeam.Name,
                    AwayTeam = m.AwayTeam.Name,
                    HomeGoals = m.Status == "scheduled" ? null : m.HomeGoals,
                    AwayGoals = m.Status == "scheduled" ? null : m.AwayGoals,
                    Status = m.Status,
                    Date = m.Date
                }).ToList()
            })
            .ToList();
    }

    private static string RoundStatus(Round round)
    {
        if (round.Matches.Count == 0)
            return "scheduled";
        if (round.Matches.All(m => m.Status == "finished"))
            return "finished";
        if (round.Matches.Any(m => m.Status is "finished" or "ongoing"))
            return "ongoing";
        return "scheduled";
    }

    private static int GetIntRule(Championship championship, string key, int fallback)
    {
        var rule = championship.ChampionshipRules.FirstOrDefault(r => r.Key == key);
        return rule != null && int.TryParse(rule.Value, out var parsed) ? parsed : fallback;
    }
}
