using System.ComponentModel.DataAnnotations;

namespace MyCup.Models;

/// <summary>
/// Represents an athlete profile that can participate in universes, championships, and match statistics.
/// </summary>
public class Player
{
    /// <summary>
    /// Unique identifier of the player.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Optional foreign key linking this player to a platform user account.
    /// </summary>
    public int? UserId { get; set; }

    /// <summary>
    /// Required foreign key identifying the universe where this player participates.
    /// </summary>
    public int UniverseId { get; set; }

    /// <summary>
    /// Public name of the player profile.
    /// </summary>
    [MaxLength(120)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Navigation reference to the linked user account when available.
    /// </summary>
    public User? User { get; set; }

    /// <summary>
    /// Navigation reference to the universe where the player is registered.
    /// </summary>
    public Universe Universe { get; set; } = null!;

    /// <summary>
    /// Entries connecting this player to championships and assigned teams.
    /// </summary>
    public ICollection<PlayerChampionship> PlayerChampionships { get; set; } = new List<PlayerChampionship>();

    /// <summary>
    /// Match statistics generated by this player over time.
    /// </summary>
    public ICollection<MatchStatistic> MatchStatistics { get; set; } = new List<MatchStatistic>();
}
